let supportedLanguages = {
  'c'    : 'c_cpp',
  'cpp'  : 'c_cpp',
  'js'   : 'javascript',
  'java' : 'java',
  'py'   : 'python',
  'css'  : 'css',
  'cs'   : 'csharp',
  'sql'  : 'mysql',
  'json' : 'json',
  'html' : 'html',
  'xml'  : 'xml',
  'php'  : 'php',
  'sh'   : 'sh',
  'lua'  : 'lua',
  'txt'  : 'text'
}

let languageNames = {
  'c_cpp'      : 'C/C++',
  'javascript' : 'Javascript',
  'java'       : 'Java',
  'python'     : 'Python',
  'css'        : 'Css',
  'csharp'     : 'C#',
  'mysql'      : 'MySql',
  'json'       : 'Json',
  'html'       : 'HTML',
  'xml'        : 'XML',
  'php'        : 'PHP',
  'sh'         : 'Bash Shell',
  'lua'        : 'Lua',
  'text'       : 'None'
}

let editorThemes = [
  "ambiance",
  "chaos",
  "chrome",
  "clouds",
  "clouds_midnight",
  "cobalt",
  "crimson_editor",
  "dawn",
  "dracula",
  "dreamweaver",
  "eclipse",
  "github",
  "gob",
  "gruvbox",
  "idle_fingers",
  "iplastic",
  "katzenmilch",
  "kr_theme",
  "kuroir",
  "merbivore",
  "merbivore_soft",
  "mono_industrial",
  "monokai",
  "pastel_on_dark",
  "solarized_dark",
  "solarized_light",
  "sqlserver",
  "terminal",
  "textmate",
  "tomorrow",
  "tomorrow_night",
  "tomorrow_night_blue",
  "tomorrow_night_bright",
  "tomorrow_night_eighties",
  "twilight",
  "vibrant_ink",
  "xcode"
]

export default { languages: supportedLanguages, languageDisplayNames: languageNames, themes: editorThemes }
